### ISSUE TITLE
Accelerated speed when walking against walls

### ISSUE THREAD

**Issue by elvisish** [wareya/GodotStairTester#4]
The player speed seems to increase when sliding against walls, I'm not entirely sure what's causing this but the stair hack doesn't fix it and it doesn't happen when I disable the stair code. Any ideas what this could be?

**Comment by wareya** [comment]
This is a consequence of how the acceleration code in the demo works rather than the collision-related stuff. It's the same "feature-bug" as wallrunning in Quake.
