### ISSUE TITLE
Jolt physics causes inconsistencies

### ISSUE THREAD

**Issue by sinewavey** [wareya/GodotStairTester#6]
Hey, just a heads up I figured you, or anyone else looking at this might want tn be aware of: the behavior is different from GD Physics to Jolt in a breaking manner.

Since Jolt - for now - is a third-party addon I don't think it's something to worry about too much, but as a warning for users in the future, be aware!

**Comment by wareya** [comment]
See also: https://github.com/wareya/GodotStairTester/issues/3

Try turning on the skipping hack.

**Comment by sinewavey** [comment]
Makes sense. I'm using a custom implementation of this, so I was in the middle of making a fresh little test with just this to see what I needed to fix for my own. Thanks for the pointer. I'll mark this as resolved.

**Comment by wareya** [comment]
Feel free to reopen if you can't fix it.

**Comment by elvisish** [comment]
I just tried this stair step example again and, yup, GDPhysics is incredible at tiny distances and really parallel angles, whereas Jolt just slides along. Can Jolt's margins be made even smaller?

EDIT: this seems to fix it:
![image](https://github.com/user-attachments/assets/a236dd15-83ed-4d2a-a606-aa9c4285e688)
